// <auto-generated />
namespace ProjektPiotrMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v104));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060110291_v104"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
